version: '3.8'

services:
  db:
    image: mysql:8.0 # ปรับเป็น MySQL 8.0 เพื่อความทันสมัย (หรือใช้ 5.7 ตามเดิมได้หากต้องการ)
    container_name: mysql_db_821
        # MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ Client รุ่นเก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8821:3306"
    volumes: #พื้นที่ในการจัดเก็บข้อมูลถาวร
      - mysql_data_821:/var/lib/mysql
    networks: 
      - weblab821
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_821
    environment:
      PMA_HOST: db # ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306 # พอร์ตมาตรฐานของ MySQL คือ 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M # เพิ่มลิมิตการอัปโหลดไฟล์ SQL
    ports:
      - "8822:80"
    depends_on: #ต้องทำงานหลังจากที่ Database พร้อมแล้ว
      - db
    networks: #สิ่งที่เราจะเชื่อมต่อ ให้อยู่ใน Network เดียวกัน
      - weblab821 
    restart: always #ให้ Container ทำงานตลอดเวลา เมื่อเกิดปัญหาจะได้รีสตาร์ทใหม่

networks:
  weblab821:
    driver: bridge #สร้าง Network แบบ Bridge คือ เชื่อมต่อระหว่าง Container ด้วยกันเอง
 
volumes:
  mysql_data_821:
    driver: local